/*
 Navicat Premium Data Transfer

 Source Server         : aliyuncs-rds
 Source Server Type    : MySQL
 Source Server Version : 80025
 Source Host           : penint-al.mysql.rds.aliyuncs.com:3306
 Source Schema         : ptw_tms_nacos

 Target Server Type    : MySQL
 Target Server Version : 80025
 File Encoding         : 65001

 Date: 20/07/2023 12:06:55
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS `config_info`;
CREATE TABLE `config_info`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_use` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `effect` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_schema` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfo_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 18 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_info
-- ----------------------------
INSERT INTO `config_info` VALUES (1, 'server-system.yaml', 'DEFAULT_GROUP', 'server:\n  port: 8201\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:p6spy:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    # url: jdbc:mysql://localhost:3306/ptw_tms_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n\n  redis:\n    database: 13\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.common.core.entity.system\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**,/common/**,/oss/**\n      scope-uris: /adminApi/**\n      scope-name: admin\n', '67ff34d107b518d7052384c56c8d20b3', '2023-07-17 00:00:00', '2023-07-17 07:42:11', 'nacos', '0:0:0:0:0:0:0:1', '', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5', 'Server-System微服务配置', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (2, 'auth.yaml', 'DEFAULT_GROUP', 'server:\n  port: 8101\nspring:\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver  \n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n\n  redis:\n    database: 13\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.common.core.entity.system\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\n\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000\n\npenint:\n  frontUrl: \'http://192.168.231.3:1024\'\n  cloud:\n    security:\n      enable: true\n      only-fetch-by-gateway: false\n      anon-uris: /actuator/**,/captcha/**,/social/**,/login,/resource/**,/signout,/customUser/queryCount/**\n      scope-uris: /client/**\n      scope-name: auth', '3aedba08cc398d6808e465a6fc89a15b', '2023-07-17 00:00:00', '2023-07-19 08:01:54', 'nacos', '0:0:0:0:0:0:0:1', '', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5', 'Auth微服务配置', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (3, 'gateway.yaml', 'DEFAULT_GROUP', 'server:\n  port: 8301\nspring:\n  cloud:\n    gateway:\n      globalcors:\n        corsConfigurations:\n          \'[/**]\':\n            allowedOrigins: \"*\"\n            allowedMethods: \"*\"\n            allowedHeaders: \"*\"\n            allowCredentials: true\n      routes:\n        - id: Cloud-Auth\n          uri: lb://Cloud-Auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            - name: Hystrix\n              args:\n                name: authfallback\n                fallbackUri: forward:/fallback/Cloud-Auth            \n        - id: Cloud-Server-System\n          uri: lb://Cloud-Server-System\n          predicates:\n            - Path=/system/**\n          filters:\n            - name: Hystrix\n              args:\n                name: systemfallback\n                fallbackUri: forward:/fallback/Cloud-Server-System\n        - id: Cloud-Server-Busi\n          uri: lb://Cloud-Server-Busi\n          predicates:\n            - Path=/busi/**\n          filters:\n            - name: Hystrix\n              args:\n                name: busifallback\n                fallbackUri: forward:/fallback/Cloud-Server-Busi\n        - id: Cloud-Server-Ques\n          uri: lb://Cloud-Server-Ques\n          predicates:\n            - Path=/ques/**\n          filters:\n            - name: Hystrix\n              args:\n                name: quesfallback\n                fallbackUri: forward:/fallback/Cloud-Server-Ques\n      loadbalancer:\n        use404: true\n      default-filters:\n        - StripPrefix=1\n  autoconfigure:\n    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration\n\npenint:\n  gateway:\n    enhance: false\n    jwt:\n      secret: 123456\n      expiration: 36000\n\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 30000\n    socialfallback:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 60000    \n\nribbon:\n  eager-load:\n    enabled: true\n\nmanagement:\n  endpoint:\n    health:\n      show-details: ALWAYS\n  endpoints:\n    web:\n      exposure:\n        include: health,info,gateway\n\n', 'f9d21e83534dfefb999b341f83b041d3', '2023-07-17 00:00:00', '2023-07-20 01:56:29', 'nacos', '0:0:0:0:0:0:0:1', '', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (8, 'server-busi.yaml', 'DEFAULT_GROUP', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:p6spy:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_busi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 13\n    host: localhost\n    port: 6379\n    # password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.busi.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**,/stat/**\n      scope-uris: /busi/**\n      scope-name: busi\n', 'e28aa7a432d4f25c47df57040ac5e459', '2023-07-17 07:58:52', '2023-07-19 08:27:18', 'nacos', '0:0:0:0:0:0:0:1', '', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5', '问卷', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (19, 'server-ques.yaml', 'DEFAULT_GROUP', 'server:\n  port: 8402\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:p6spy:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_ques?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 13\n    host: localhost\n    port: 6379\n    # password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /ques/**\n      scope-name: ques\n', '9da8d2c1366e9b380fbadfa3ac30b5a4', '2023-07-20 01:54:20', '2023-07-20 02:44:18', 'nacos', '0:0:0:0:0:0:0:1', '', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5', '问卷', '', '', 'yaml', '');

-- ----------------------------
-- Table structure for config_info_aggr
-- ----------------------------
DROP TABLE IF EXISTS `config_info_aggr`;
CREATE TABLE `config_info_aggr`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'datum_id',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '内容',
  `gmt_modified` datetime NOT NULL COMMENT '修改时间',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfoaggr_datagrouptenantdatum`(`data_id`, `group_id`, `tenant_id`, `datum_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '增加租户字段' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_info_aggr
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS `config_info_beta`;
CREATE TABLE `config_info_beta`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfobeta_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_beta' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_info_beta
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS `config_info_tag`;
CREATE TABLE `config_info_tag`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfotag_datagrouptenanttag`(`data_id`, `group_id`, `tenant_id`, `tag_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_tag' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_info_tag
-- ----------------------------

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS `config_tags_relation`;
CREATE TABLE `config_tags_relation`  (
  `id` bigint NOT NULL COMMENT 'id',
  `tag_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`) USING BTREE,
  UNIQUE INDEX `uk_configtagrelation_configidtag`(`id`, `tag_name`, `tag_type`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_tag_relation' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of config_tags_relation
-- ----------------------------

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS `group_capacity`;
CREATE TABLE `group_capacity`  (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Group ID，空字符表示整个集群',
  `quota` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数，，0表示使用默认值',
  `max_aggr_size` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_group_id`(`group_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '集群、各Group容量信息表' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of group_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS `his_config_info`;
CREATE TABLE `his_config_info`  (
  `id` bigint UNSIGNED NOT NULL,
  `nid` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `op_type` char(10) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`nid`) USING BTREE,
  INDEX `idx_gmt_create`(`gmt_create`) USING BTREE,
  INDEX `idx_gmt_modified`(`gmt_modified`) USING BTREE,
  INDEX `idx_did`(`data_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 20 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '多租户改造' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of his_config_info
-- ----------------------------
INSERT INTO `his_config_info` VALUES (0, 1, 'server-system.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8201\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: sep\n    password: sep123456@\n    url: jdbc:p6spy:mysql://localhost:3306/security_emergency_platform_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://localhost:3306/security_emergency_platform_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n\n  redis:\n    database: 1\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.common.core.entity.system\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**,/common/**,/oss/**\n      scope-uris: /adminApi/**\n      scope-name: admin\n', 'ee8cfa177c0350092470debee625c8d8', '2023-07-17 00:00:00', '2023-07-17 00:00:00', NULL, '0:0:0:0:0:0:0:1', 'I', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (0, 2, 'auth.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8101\nspring:\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver  \n    username: sep\n    password: sep123456@\n    url: jdbc:mysql://localhost:3306/security_emergency_platform_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n\n  redis:\n    database: 1\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.common.core.entity.system\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\n\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000\n\npenint:\n  frontUrl: \'http://192.168.231.3:1024\'\n  cloud:\n    security:\n      enable: true\n      only-fetch-by-gateway: false\n      anon-uris: /actuator/**,/captcha/**,/social/**,/login,/resource/**,/signout\n      scope-uris: /client/**\n      scope-name: auth', '88e19bcffcd068d6899613f568067edb', '2023-07-17 00:00:00', '2023-07-17 00:00:00', NULL, '0:0:0:0:0:0:0:1', 'I', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (0, 3, 'gateway.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8301\nspring:\n  cloud:\n    gateway:\n      globalcors:\n        corsConfigurations:\n          \'[/**]\':\n            allowedOrigins: \"*\"\n            allowedMethods: \"*\"\n            allowedHeaders: \"*\"\n            allowCredentials: true\n      routes:\n        - id: Cloud-Auth\n          uri: lb://Cloud-Auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            - name: Hystrix\n              args:\n                name: authfallback\n                fallbackUri: forward:/fallback/Cloud-Auth            \n        - id: Cloud-Server-System\n          uri: lb://Cloud-Server-System\n          predicates:\n            - Path=/system/**\n          filters:\n            - name: Hystrix\n              args:\n                name: systemfallback\n                fallbackUri: forward:/fallback/Cloud-Server-System\n        - id: Cloud-Server-Sep\n          uri: lb://Cloud-Server-Sep\n          predicates:\n            - Path=/sep/**\n          filters:\n            - name: Hystrix\n              args:\n                name: sepfallback\n                fallbackUri: forward:/fallback/Cloud-Server-Sep\n      loadbalancer:\n        use404: true\n      default-filters:\n        - StripPrefix=1\n  autoconfigure:\n    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration\n\npenint:\n  gateway:\n    enhance: false\n    jwt:\n      secret: 123456\n      expiration: 36000\n\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 30000\n    socialfallback:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 60000    \n\nribbon:\n  eager-load:\n    enabled: true\n\nmanagement:\n  endpoint:\n    health:\n      show-details: ALWAYS\n  endpoints:\n    web:\n      exposure:\n        include: health,info,gateway\n\n', '888faeb6dad1ed8640e2c120b0fab69d', '2023-07-17 00:00:00', '2023-07-17 00:00:00', NULL, '0:0:0:0:0:0:0:1', 'I', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (0, 4, 'server-sep.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: sep\n    password: sep123456@\n    url: jdbc:p6spy:mysql://localhost:3306/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 1\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /sepApi/**\n      scope-name: sep\n', '893fae92660590fa974270bf80746a05', '2023-07-17 00:00:00', '2023-07-17 00:00:00', NULL, '0:0:0:0:0:0:0:1', 'I', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (2, 5, 'auth.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8101\nspring:\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver  \n    username: sep\n    password: sep123456@\n    url: jdbc:mysql://localhost:3306/security_emergency_platform_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n\n  redis:\n    database: 1\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.common.core.entity.system\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\n\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000\n\npenint:\n  frontUrl: \'http://192.168.231.3:1024\'\n  cloud:\n    security:\n      enable: true\n      only-fetch-by-gateway: false\n      anon-uris: /actuator/**,/captcha/**,/social/**,/login,/resource/**,/signout\n      scope-uris: /client/**\n      scope-name: auth', '88e19bcffcd068d6899613f568067edb', '2023-07-17 15:34:47', '2023-07-17 07:34:46', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (1, 6, 'server-system.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8201\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: sep\n    password: sep123456@\n    url: jdbc:p6spy:mysql://localhost:3306/security_emergency_platform_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://localhost:3306/security_emergency_platform_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n\n  redis:\n    database: 1\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.common.core.entity.system\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**,/common/**,/oss/**\n      scope-uris: /adminApi/**\n      scope-name: admin\n', 'ee8cfa177c0350092470debee625c8d8', '2023-07-17 15:36:16', '2023-07-17 07:36:14', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (1, 7, 'server-system.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8201\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    # url: jdbc:mysql://localhost:3306/ptw_tms_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n\n  redis:\n    database: 13\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.common.core.entity.system\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**,/common/**,/oss/**\n      scope-uris: /adminApi/**\n      scope-name: admin\n', '515f370f7d028484116e10bee2f00eac', '2023-07-17 15:42:12', '2023-07-17 07:42:11', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (0, 8, 'server-busi.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: sep\n    password: sep123456@\n    url: jdbc:p6spy:mysql://localhost:3306/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 1\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /sepApi/**\n      scope-name: sep\n', '893fae92660590fa974270bf80746a05', '2023-07-17 15:58:52', '2023-07-17 07:58:52', NULL, '0:0:0:0:0:0:0:1', 'I', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (4, 9, 'server-sep.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: sep\n    password: sep123456@\n    url: jdbc:p6spy:mysql://localhost:3306/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 1\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /sepApi/**\n      scope-name: sep\n', '893fae92660590fa974270bf80746a05', '2023-07-17 15:58:56', '2023-07-17 07:58:55', 'nacos', '0:0:0:0:0:0:0:1', 'D', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (3, 10, 'gateway.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8301\nspring:\n  cloud:\n    gateway:\n      globalcors:\n        corsConfigurations:\n          \'[/**]\':\n            allowedOrigins: \"*\"\n            allowedMethods: \"*\"\n            allowedHeaders: \"*\"\n            allowCredentials: true\n      routes:\n        - id: Cloud-Auth\n          uri: lb://Cloud-Auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            - name: Hystrix\n              args:\n                name: authfallback\n                fallbackUri: forward:/fallback/Cloud-Auth            \n        - id: Cloud-Server-System\n          uri: lb://Cloud-Server-System\n          predicates:\n            - Path=/system/**\n          filters:\n            - name: Hystrix\n              args:\n                name: systemfallback\n                fallbackUri: forward:/fallback/Cloud-Server-System\n        - id: Cloud-Server-Sep\n          uri: lb://Cloud-Server-Sep\n          predicates:\n            - Path=/sep/**\n          filters:\n            - name: Hystrix\n              args:\n                name: sepfallback\n                fallbackUri: forward:/fallback/Cloud-Server-Sep\n      loadbalancer:\n        use404: true\n      default-filters:\n        - StripPrefix=1\n  autoconfigure:\n    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration\n\npenint:\n  gateway:\n    enhance: false\n    jwt:\n      secret: 123456\n      expiration: 36000\n\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 30000\n    socialfallback:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 60000    \n\nribbon:\n  eager-load:\n    enabled: true\n\nmanagement:\n  endpoint:\n    health:\n      show-details: ALWAYS\n  endpoints:\n    web:\n      exposure:\n        include: health,info,gateway\n\n', '888faeb6dad1ed8640e2c120b0fab69d', '2023-07-17 16:02:55', '2023-07-17 08:02:54', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (8, 11, 'server-busi.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: sep\n    password: sep123456@\n    url: jdbc:p6spy:mysql://localhost:3306/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 1\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /sepApi/**\n      scope-name: sep\n', '893fae92660590fa974270bf80746a05', '2023-07-17 16:03:06', '2023-07-17 08:03:05', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (8, 12, 'server-busi.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: sep\n    password: sep123456@\n    url: jdbc:p6spy:mysql://localhost:3306/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 1\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /sepApi/**\n      scope-name: busi\n', 'eb4202d2ce635eb075f62a893af720d8', '2023-07-17 16:03:16', '2023-07-17 08:03:15', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (8, 13, 'server-busi.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: sep\n    password: sep123456@\n    url: jdbc:p6spy:mysql://localhost:3306/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 1\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /busiApi/**\n      scope-name: busi\n', 'eaa2ee8357799dff66cae86624090fb5', '2023-07-17 16:03:46', '2023-07-17 08:03:45', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (8, 14, 'server-busi.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: sep\n    password: sep123456@\n    url: jdbc:p6spy:mysql://localhost:3306/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 1\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /busi/**\n      scope-name: busi\n', '044b33f9a6d8efe4bf9af59933782e2e', '2023-07-17 16:04:37', '2023-07-17 08:04:36', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (8, 15, 'server-busi.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:p6spy:mysql://localhost:3306/ptw_tms_busi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 13\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /busi/**\n      scope-name: busi\n', '06a00409ab30c6e12af4155ad74d0049', '2023-07-17 16:07:36', '2023-07-17 08:07:35', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (8, 16, 'server-busi.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:p6spy:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_busi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 13\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /busi/**\n      scope-name: busi\n', '8057f5c883268713b60edc707fda75b3', '2023-07-18 21:50:34', '2023-07-18 13:50:33', 'nacos', '192.168.1.4', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (8, 17, 'server-busi.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:p6spy:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_busi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 13\n    host: localhost\n    port: 6379\n    # password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /busi/**\n      scope-name: busi\n', 'ca3299b2fde1bb711a24ad912a410a39', '2023-07-19 15:59:11', '2023-07-19 07:59:10', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (2, 18, 'auth.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8101\nspring:\n  datasource:\n    driver-class-name: com.mysql.cj.jdbc.Driver  \n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n\n  redis:\n    database: 13\n    host: 192.168.1.5\n    port: 6379\n    password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.common.core.entity.system\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\n\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000\n\npenint:\n  frontUrl: \'http://192.168.231.3:1024\'\n  cloud:\n    security:\n      enable: true\n      only-fetch-by-gateway: false\n      anon-uris: /actuator/**,/captcha/**,/social/**,/login,/resource/**,/signout\n      scope-uris: /client/**\n      scope-name: auth', '3702676c47bf45db689ec3676c36f3d4', '2023-07-19 16:01:56', '2023-07-19 08:01:54', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (8, 19, 'server-busi.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:p6spy:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_busi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 13\n    host: localhost\n    port: 6379\n    # password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**,/stat/**\n      scope-uris: /busi/**\n      scope-name: busi\n', 'd2c65c1fef7afdabf35ecfed2b1541be', '2023-07-19 16:27:20', '2023-07-19 08:27:18', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (0, 20, 'server-ques.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:p6spy:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_busi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 13\n    host: localhost\n    port: 6379\n    # password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.busi.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**,/stat/**\n      scope-uris: /busi/**\n      scope-name: busi\n', 'e28aa7a432d4f25c47df57040ac5e459', '2023-07-20 09:54:21', '2023-07-20 01:54:20', NULL, '0:0:0:0:0:0:0:1', 'I', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (19, 21, 'server-ques.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:p6spy:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_busi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 13\n    host: localhost\n    port: 6379\n    # password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.busi.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**,/stat/**\n      scope-uris: /busi/**\n      scope-name: busi\n', 'e28aa7a432d4f25c47df57040ac5e459', '2023-07-20 09:55:08', '2023-07-20 01:55:07', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (3, 22, 'gateway.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8301\nspring:\n  cloud:\n    gateway:\n      globalcors:\n        corsConfigurations:\n          \'[/**]\':\n            allowedOrigins: \"*\"\n            allowedMethods: \"*\"\n            allowedHeaders: \"*\"\n            allowCredentials: true\n      routes:\n        - id: Cloud-Auth\n          uri: lb://Cloud-Auth\n          predicates:\n            - Path=/auth/**\n          filters:\n            - name: Hystrix\n              args:\n                name: authfallback\n                fallbackUri: forward:/fallback/Cloud-Auth            \n        - id: Cloud-Server-System\n          uri: lb://Cloud-Server-System\n          predicates:\n            - Path=/system/**\n          filters:\n            - name: Hystrix\n              args:\n                name: systemfallback\n                fallbackUri: forward:/fallback/Cloud-Server-System\n        - id: Cloud-Server-Busi\n          uri: lb://Cloud-Server-Busi\n          predicates:\n            - Path=/busi/**\n          filters:\n            - name: Hystrix\n              args:\n                name: busifallback\n                fallbackUri: forward:/fallback/Cloud-Server-Busi\n      loadbalancer:\n        use404: true\n      default-filters:\n        - StripPrefix=1\n  autoconfigure:\n    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration\n\npenint:\n  gateway:\n    enhance: false\n    jwt:\n      secret: 123456\n      expiration: 36000\n\nhystrix:\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 30000\n    socialfallback:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 60000    \n\nribbon:\n  eager-load:\n    enabled: true\n\nmanagement:\n  endpoint:\n    health:\n      show-details: ALWAYS\n  endpoints:\n    web:\n      exposure:\n        include: health,info,gateway\n\n', '0af46a1502321a0f29e5d2dd477a0c90', '2023-07-20 09:56:29', '2023-07-20 01:56:29', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (19, 23, 'server-ques.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8401\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:p6spy:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_ques?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 13\n    host: localhost\n    port: 6379\n    # password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /ques/**\n      scope-name: ques\n', 'e0b8d430937292e71daf1cd5ffebb5d9', '2023-07-20 10:40:31', '2023-07-20 02:40:30', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (19, 24, 'server-ques.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8501\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:p6spy:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_ques?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 13\n    host: localhost\n    port: 6379\n    # password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /ques/**\n      scope-name: ques\n', 'dff9cb32ca7c8fe68cb1c168ee7b47e4', '2023-07-20 10:43:44', '2023-07-20 02:43:44', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');
INSERT INTO `his_config_info` VALUES (19, 25, 'server-ques.yaml', 'DEFAULT_GROUP', '', 'server:\n  port: 8302\n    \nspring:\n  datasource:\n    # driver-class-name: com.mysql.cj.jdbc.Driver\n    driver-class-name: com.p6spy.engine.spy.P6SpyDriver\n    username: ptw_tms\n    password: ptw_tms@123\n    url: jdbc:p6spy:mysql://penint-al.mysql.rds.aliyuncs.com:3306/ptw_tms_ques?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai  \n    # url: jdbc:mysql://${host}/security_emergency_platform_sep?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai\n    hikari:\n      connection-timeout: 30000\n      max-lifetime: 1800000\n      max-pool-size: 15\n      min-idle: 5\n      connection-test-query: select 1\n      pool-name: HikariCP\n  aop:\n    proxy-target-class: true\n  jackson:\n    date-format: yyyy-MM-dd HH:mm:ss\n    time-zone: GMT+8\n  freemarker:\n    check-template-location: false\n\n  redis:\n    database: 13\n    host: localhost\n    port: 6379\n    # password: DFdoSRnACPApuczl\n    lettuce:\n      pool:\n        min-idle: 8\n        max-idle: 500\n        max-active: 2000\n        max-wait: 10000\n    timeout: 5000\n\nmybatis-plus:\n  type-aliases-package: vip.penint.cloud.server.ques.entity\n  mapper-locations: classpath:mapper/*.xml\n  configuration:\n    jdbc-type-for-null: null\n  global-config:\n    banner: false\nsecurity:\n  oauth2:\n    resource:\n      id: ${spring.application.name}\n      user-info-uri: http://localhost:8301/auth/user\n\ninfo:\n  app:\n    name: ${spring.application.name}\n    description: \"@project.description@\"\n    version: \"@project.version@\"\n\nmanagement:\n  endpoints:\n    web:\n      exposure:\n        include: \'*\'\n  endpoint:\n    health:\n      show-details: ALWAYS\n\nfeign:\n  hystrix:\n    enabled: true\nhystrix:\n  shareSecurityContext: true\n  command:\n    default:\n      execution:\n        isolation:\n          thread:\n            timeoutInMilliseconds: 3000         \npenint:\n  cloud:\n    security:\n      enable: true\n      anon-uris: /actuator/**\n      scope-uris: /ques/**\n      scope-name: ques\n', 'cb0f1621440da72584777362d23b6bc3', '2023-07-20 10:44:18', '2023-07-20 02:44:18', 'nacos', '0:0:0:0:0:0:0:1', 'U', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5');

-- ----------------------------
-- Table structure for permissions
-- ----------------------------
DROP TABLE IF EXISTS `permissions`;
CREATE TABLE `permissions`  (
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `resource` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `action` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  UNIQUE INDEX `uk_role_permission`(`role`, `resource`, `action`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of permissions
-- ----------------------------

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  UNIQUE INDEX `idx_user_role`(`username`, `role`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO `roles` VALUES ('nacos', 'ROLE_ADMIN');

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS `tenant_capacity`;
CREATE TABLE `tenant_capacity`  (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数',
  `max_aggr_size` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '租户容量信息表' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of tenant_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS `tenant_info`;
CREATE TABLE `tenant_info`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_info_kptenantid`(`kp`, `tenant_id`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'tenant_info' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of tenant_info
-- ----------------------------
INSERT INTO `tenant_info` VALUES (1, '1', '69b2ffc0-c439-48c6-8f16-96be4b3d85c5', 'ptw_tms', 'ptw_tms', 'nacos', 1683527053133, 1689578806318);

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `password` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);

SET FOREIGN_KEY_CHECKS = 1;
